EXAMPLE_BOOKING = {
    "hotel": "City Hotel - Seoul",
    "lead_time": 45,
    "arrival_date_month": "July",
    "arrival_date_week_number": 29,
    "arrival_date_day_of_month": 18,
    "stays_in_weekend_nights": 2,
    "stays_in_week_nights": 3,
    "adults": 2,
    "children": 1,
    "babies": 0,
    "meal": "BB",
    "country": "KOR",
    "market_segment": "Online TA",
    "distribution_channel": "TA/TO",
    "is_repeated_guest": 0,
    "previous_cancellations": 0,
    "previous_bookings_not_canceled": 1,
    "reserved_room_type": "A",
    "assigned_room_type": "A",
    "booking_changes": 0,
    "deposit_type": "No Deposit",
    "agent": 9,
    "company": None,
    "days_in_waiting_list": 0,
    "customer_type": "Transient",
    "adr": 110.5,
    "required_car_parking_spaces": 0,
    "total_of_special_requests": 1,
    "city": "Seoul",
}
